In [1]:
import pandas as pd 

df_contracts = pd.read_csv('../data/contracts.csv')
df_customers = pd.read_csv('../data/customers.csv')
df_customers.rename(columns={'id': 'customer_id'}, inplace= True)
df_customers.set_index('customer_id', inplace = True)
df_contracts = df_contracts.set_index('customer_id')
df = df_contracts.join(df_customers, how='left')
df.head(25)

,contract_id,contract_start,contract_term,deposit,monthly_amt,company,sector,industry,email,address,city,state,zip
customer_id,,,,,,,,,,,,,
1,41,5/31/19,24,"$86,000.00","$11,200.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,358,6/18/19,13,"$74,000.00","$19,000.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,400,8/11/19,19,"$38,000.00","$8,800.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,424,3/13/19,15,"$77,000.00","$14,300.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,438,10/16/19,22,"$39,000.00","$20,000.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,657,8/27/19,24,"$67,000.00","$22,400.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,848,11/15/19,11,"$34,000.00","$10,700.00",Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
2,308,3/28/19,24,"$14,000.00","$6,900.00",Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
2,416,12/25/19,18,"$63,000.00","$8,900.00",Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
2,645,9/20/19,3,"$34,000.00","$19,100.00",Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
2,754,11/15/19,12,"$76,000.00","$6,600.00",Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
2,954,1/31/19,14,"$15,000.00","$24,300.00",Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
3,361,8/11/19,1,"$49,000.00","$17,900.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,596,12/1/19,1,"$19,000.00","$13,500.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,603,2/8/19,7,"$76,000.00","$7,900.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,759,6/3/19,9,"$91,000.00","$10,900.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,953,3/7/19,18,"$38,000.00","$9,900.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,1000,3/19/19,16,"$23,000.00","$15,700.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
4,378,12/10/19,24,"$46,000.00","$15,700.00",Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
4,525,1/8/19,15,"$50,000.00","$24,500.00",Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
4,896,2/5/19,18,"$85,000.00","$5,600.00",Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
5,501,10/23/19,5,"$75,000.00","$19,300.00",Jabberstorm,Technology,Computer Software: Prepackaged Software,pscallon4@fc2.com,4 Moose Way,Terre Haute,IN,47805
5,707,5/23/19,6,"$46,000.00","$19,600.00",Jabberstorm,Technology,Computer Software: Prepackaged Software,pscallon4@fc2.com,4 Moose Way,Terre Haute,IN,47805
6,11,12/7/19,4,"$26,000.00","$19,100.00",Teklist,Technology,Radio And Television Broadcasting And Communic...,kformigli5@symantec.com,085 Messerschmidt Street,San Antonio,TX,78245
6,26,3/3/19,17,"$69,000.00","$19,400.00",Teklist,Technology,Radio And Television Broadcasting And Communic...,kformigli5@symantec.com,085 Messerschmidt Street,San Antonio,TX,78245

In [2]:
df.groupby('state').agg({'contract_id':'count', 'company': pd.Series.nunique}).sort_values('company', ascending=False)

       contract_id  company
state
TX             104       21
CA              88       17
FL              70       15
NY              43       11
WA              54        9
DC              32        8
PA              29        7
KS              43        7
VA              35        7
OH              33        6
LA              33        6
WI              24        6
CO              34        6
OR              22        5
OK              34        5
AZ              22        5
MO              26        5
GA              15        4
MD              18        4
MI              20        4
IL              23        4
TN              16        4
NC              25        4
ID              18        3
NE              22        3
MN              18        3
DE              14        3
IN              11        3
NV               9        2
CT              11        2
SC               5        1
AK               8        1
ME               4        1
MS               6        1
AL               7        1
MA               6        1
KY              11        1
AR               2        1
WV               5        1

In [3]:
df.loc[df['contract_term'] <2]

,contract_id,contract_start,contract_term,deposit,monthly_amt,company,sector,industry,email,address,city,state,zip
customer_id,,,,,,,,,,,,,
3,361,8/11/19,1,"$49,000.00","$17,900.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,596,12/1/19,1,"$19,000.00","$13,500.00",Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
15,84,4/4/19,1,"$65,000.00","$22,600.00",Buzzbean,Consumer Non-Durables,Consumer Electronics/Appliances,reslere@mac.com,7472 Tony Avenue,Bronx,NY,10459
15,105,1/31/19,1,"$61,000.00","$20,200.00",Buzzbean,Consumer Non-Durables,Consumer Electronics/Appliances,reslere@mac.com,7472 Tony Avenue,Bronx,NY,10459
16,211,6/15/19,1,"$34,000.00","$14,200.00",Kwinu,NaN,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215
21,309,12/9/19,1,"$44,000.00","$22,700.00",Tanoodle,NaN,NaN,fchaytork@sogou.com,1 Armistice Avenue,Pueblo,CO,81005
22,503,11/10/19,1,"$64,000.00","$20,400.00",Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764
22,548,7/13/19,1,"$55,000.00","$5,300.00",Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764
29,677,8/22/19,1,"$24,000.00","$20,400.00",Yodoo,NaN,NaN,lwinstanleys@noaa.gov,3 Oneill Court,Tucson,AZ,85715
40,142,10/19/19,1,"$25,000.00","$24,800.00",Feedfish,Finance,Investment Bankers/Brokers/Service,rnodes13@google.es,51602 Kenwood Plaza,Columbus,OH,43226
51,628,7/8/19,1,"$67,000.00","$24,000.00",Brainlounge,NaN,NaN,corpin1e@icio.us,35 Barnett Trail,Aurora,CO,80044
52,556,6/12/19,1,"$53,000.00","$8,600.00",Jabbertype,NaN,NaN,ycole1f@facebook.com,859 Summer Ridge Alley,Topeka,KS,66642
53,473,5/10/19,1,"$22,000.00","$8,100.00",Centidel,Finance,Major Banks,fsutherby1g@reuters.com,93 Melvin Park,San Francisco,CA,94164
55,393,6/3/19,1,"$60,000.00","$22,400.00",Eimbee,Health Care,Major Pharmaceuticals,dmilbourne1i@g.co,38460 Dixon Way,Round Rock,TX,78682
55,653,11/28/19,1,"$77,000.00","$5,500.00",Eimbee,Health Care,Major Pharmaceuticals,dmilbourne1i@g.co,38460 Dixon Way,Round Rock,TX,78682
60,23,7/13/19,1,"$29,000.00","$21,400.00",Zoomdog,Consumer Services,Real Estate Investment Trusts,scolston1n@zdnet.com,0 Barnett Alley,Baltimore,MD,21229
62,486,10/7/19,1,"$68,000.00","$24,900.00",Dabfeed,Energy,Natural Gas Distribution,abader1p@dailymotion.com,1 Jackson Parkway,Oklahoma City,OK,73173
62,964,6/3/19,1,"$37,000.00","$17,700.00",Dabfeed,Energy,Natural Gas Distribution,abader1p@dailymotion.com,1 Jackson Parkway,Oklahoma City,OK,73173
64,186,3/11/19,1,"$57,000.00","$23,100.00",Flipbug,Public Utilities,Natural Gas Distribution,eleall1r@harvard.edu,7938 Hermina Park,Ocala,FL,34479
66,301,12/9/19,1,"$14,000.00","$15,700.00",Demizz,Basic Industries,Major Chemicals,adyas1t@infoseek.co.jp,60701 Shopko Pass,Washington,DC,20436
70,352,3/24/19,1,"$37,000.00","$17,900.00",Thoughtmix,Technology,Computer peripheral equipment,nblaine1x@prweb.com,1790 Donald Hill,Boise,ID,83757
70,665,9/27/19,1,"$22,000.00","$24,300.00",Thoughtmix,Technology,Computer peripheral equipment,nblaine1x@prweb.com,1790 Donald Hill,Boise,ID,83757
77,448,10/27/19,1,"$62,000.00","$16,400.00",Mycat,Health Care,Other Pharmaceuticals,whucke24@wikipedia.org,33 Summer Ridge Pass,Decatur,GA,30033
80,758,1/24/19,1,"$28,000.00","$7,000.00",Twitterlist,Consumer Non-Durables,Apparel,bmurfett27@smugmug.com,14202 Toban Pass,Silver Spring,MD,20910
81,656,2/1/19,1,"$45,000.00","$15,700.00",Gigazoom,Consumer Services,Hotels/Resorts,oscoates28@cnet.com,21814 Waubesa Plaza,Oklahoma City,OK,73109
83,420,4/15/19,1,"$71,000.00","$12,000.00",Babbleset,Consumer Services,Farming/Seeds/Milling,bwake2a@cnn.com,0 Orin Plaza,Kansas City,MO,64114
83,956,8/18/19,1,"$43,000.00","$21,400.00",Babbleset,Consumer Services,Farming/Seeds/Milling,bwake2a@cnn.com,0 Orin Plaza,Kansas City,MO,64114
88,374,5/1/19,1,"$32,000.00","$7,000.00",Photobug,Finance,Major Banks,mrosenwald2f@reuters.com,8 Village Place,Kansas City,MO,64187
92,760,12/28/19,1,"$31,000.00","$23,900.00",Kayveo,Health Care,Major Pharmaceuticals,htocher2j@gmpg.org,8 Debra Place,New Orleans,LA,70129
93,375,3/16/19,1,"$39,000.00","$8,000.00",Bluezoom,Public Utilities,Telecommunications Equipment,ybrickhill2k@whitehouse.gov,19 Vidon Place,Pasadena,CA,91186
95,85,8/13/19,1,"$17,000.00","$21,700.00",Fanoodle,Technology,Electrical Products,dkohen2m@a8.net,812 Northland Circle,Tulsa,OK,74156
96,257,7/2/19,1,"$96,000.00","$23,200.00",Devify,Finance,Major Banks,apittman2n@i2i.jp,0 Stoughton Street,Schenectady,NY,12325
98,776,7/12/19,1,"$86,000.00","$20,900.00",Oloo,NaN,NaN,dhaugeh2p@census.gov,85511 Vahlen Avenue,Richmond,VA,23237
107,278,4/21/19,1,"$94,000.00","$17,400.00",Flashset,Health Care,Medical Specialities,mstummeyer2y@npr.org,236 Weeping Birch Parkway,Dallas,TX,75216
111,132,8/14/19,1,"$93,000.00","$6,000.00",Devcast,Consumer Services,Hotels/Resorts,pabelevitz32@seesaa.net,8700 Roxbury Street,Morgantown,WV,26505
121,491,11/6/19,1,"$12,000.00","$9,600.00",Zoonoodle,Health Care,Major Pharmaceuticals,vgarraway3c@sina.com.cn,1709 Waxwing Park,Los Angeles,CA,90094
128,248,3/17/19,1,"$19,000.00","$6,300.00",Zoombox,Energy,Oil Refining/Marketing,bhowlett3j@hhs.gov,43 Autumn Leaf Drive,Philadelphia,PA,19146
129,388,5/9/19,1,"$59,000.00","$8,200.00",Edgetag,NaN,NaN,hwinship3k@rediff.com,32 Pennsylvania Point,Las Vegas,NV,89155
131,492,5/22/19,1,"$81,000.00","$13,200.00",Midel,Finance,Investment Managers,cdrennan3m@artisteer.com,0 Warner Point,Topeka,KS,66617
134,191,4/19/19,1,"$20,000.00","$8,500.00",Zava,Capital Goods,Industrial Specialties,tborges3p@mapy.cz,5 Magdeline Plaza,Wilmington,DE,19886
143,321,1/23/19,1,"$15,000.00","$5,900.00",Thoughtblab,NaN,NaN,htonna3y@wikimedia.org,23 Algoma Road,Clearwater,FL,33758
156,616,1/31/19,1,"$16,000.00","$23,200.00",Omba,Energy,Coal Mining,mjeandin4b@nih.gov,4 Kinsman Plaza,Austin,TX,78749
163,697,9/12/19,1,"$15,000.00","$13,400.00",Feedbug,NaN,NaN,csemeradova4i@irs.gov,3256 Bobwhite Point,Boise,ID,83732
171,814,7/6/19,1,"$49,000.00","$9,300.00",Geba,Consumer Durables,Automotive Aftermarket,cazemar4q@hhs.gov,3 Riverside Center,Tulsa,OK,74141
173,713,3/28/19,1,"$52,000.00","$18,900.00",Jabberstorm,Consumer Non-Durables,Beverages (Production/Distribution),apickthall4s@wordpress.com,454 High Crossing Court,Raleigh,NC,27626
183,944,3/20/19,1,"$39,000.00","$9,600.00",Bubblebox,Finance,Major Banks,kklageman52@about.me,6298 Maryland Center,Erie,PA,16510
187,226,10/13/19,1,"$77,000.00","$9,600.00",Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
187,768,11/2/19,1,"$94,000.00","$12,700.00",Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
193,536,3/3/19,1,"$44,000.00","$17,800.00",Mymm,NaN,NaN,vfair5c@deviantart.com,3844 Clarendon Court,Austin,TX,78759
200,973,8/21/19,1,"$47,000.00","$12,300.00",Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055

In [4]:
df['sector'] = df['sector'].fillna('')
df.loc[df['contract_term'] < 2]

,contract_id,contract_start,contract_term,deposit,monthly_amt,company,sector,industry,email,address,city,state,zip
customer_id,,,,,,,,,,,,,
3,361,8/11/19,1,"$49,000.00","$17,900.00",Twitterworks,,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,596,12/1/19,1,"$19,000.00","$13,500.00",Twitterworks,,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
15,84,4/4/19,1,"$65,000.00","$22,600.00",Buzzbean,Consumer Non-Durables,Consumer Electronics/Appliances,reslere@mac.com,7472 Tony Avenue,Bronx,NY,10459
15,105,1/31/19,1,"$61,000.00","$20,200.00",Buzzbean,Consumer Non-Durables,Consumer Electronics/Appliances,reslere@mac.com,7472 Tony Avenue,Bronx,NY,10459
16,211,6/15/19,1,"$34,000.00","$14,200.00",Kwinu,,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215
21,309,12/9/19,1,"$44,000.00","$22,700.00",Tanoodle,,NaN,fchaytork@sogou.com,1 Armistice Avenue,Pueblo,CO,81005
22,503,11/10/19,1,"$64,000.00","$20,400.00",Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764
22,548,7/13/19,1,"$55,000.00","$5,300.00",Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764
29,677,8/22/19,1,"$24,000.00","$20,400.00",Yodoo,,NaN,lwinstanleys@noaa.gov,3 Oneill Court,Tucson,AZ,85715
40,142,10/19/19,1,"$25,000.00","$24,800.00",Feedfish,Finance,Investment Bankers/Brokers/Service,rnodes13@google.es,51602 Kenwood Plaza,Columbus,OH,43226
51,628,7/8/19,1,"$67,000.00","$24,000.00",Brainlounge,,NaN,corpin1e@icio.us,35 Barnett Trail,Aurora,CO,80044
52,556,6/12/19,1,"$53,000.00","$8,600.00",Jabbertype,,NaN,ycole1f@facebook.com,859 Summer Ridge Alley,Topeka,KS,66642
53,473,5/10/19,1,"$22,000.00","$8,100.00",Centidel,Finance,Major Banks,fsutherby1g@reuters.com,93 Melvin Park,San Francisco,CA,94164
55,393,6/3/19,1,"$60,000.00","$22,400.00",Eimbee,Health Care,Major Pharmaceuticals,dmilbourne1i@g.co,38460 Dixon Way,Round Rock,TX,78682
55,653,11/28/19,1,"$77,000.00","$5,500.00",Eimbee,Health Care,Major Pharmaceuticals,dmilbourne1i@g.co,38460 Dixon Way,Round Rock,TX,78682
60,23,7/13/19,1,"$29,000.00","$21,400.00",Zoomdog,Consumer Services,Real Estate Investment Trusts,scolston1n@zdnet.com,0 Barnett Alley,Baltimore,MD,21229
62,486,10/7/19,1,"$68,000.00","$24,900.00",Dabfeed,Energy,Natural Gas Distribution,abader1p@dailymotion.com,1 Jackson Parkway,Oklahoma City,OK,73173
62,964,6/3/19,1,"$37,000.00","$17,700.00",Dabfeed,Energy,Natural Gas Distribution,abader1p@dailymotion.com,1 Jackson Parkway,Oklahoma City,OK,73173
64,186,3/11/19,1,"$57,000.00","$23,100.00",Flipbug,Public Utilities,Natural Gas Distribution,eleall1r@harvard.edu,7938 Hermina Park,Ocala,FL,34479
66,301,12/9/19,1,"$14,000.00","$15,700.00",Demizz,Basic Industries,Major Chemicals,adyas1t@infoseek.co.jp,60701 Shopko Pass,Washington,DC,20436
70,352,3/24/19,1,"$37,000.00","$17,900.00",Thoughtmix,Technology,Computer peripheral equipment,nblaine1x@prweb.com,1790 Donald Hill,Boise,ID,83757
70,665,9/27/19,1,"$22,000.00","$24,300.00",Thoughtmix,Technology,Computer peripheral equipment,nblaine1x@prweb.com,1790 Donald Hill,Boise,ID,83757
77,448,10/27/19,1,"$62,000.00","$16,400.00",Mycat,Health Care,Other Pharmaceuticals,whucke24@wikipedia.org,33 Summer Ridge Pass,Decatur,GA,30033
80,758,1/24/19,1,"$28,000.00","$7,000.00",Twitterlist,Consumer Non-Durables,Apparel,bmurfett27@smugmug.com,14202 Toban Pass,Silver Spring,MD,20910
81,656,2/1/19,1,"$45,000.00","$15,700.00",Gigazoom,Consumer Services,Hotels/Resorts,oscoates28@cnet.com,21814 Waubesa Plaza,Oklahoma City,OK,73109
83,420,4/15/19,1,"$71,000.00","$12,000.00",Babbleset,Consumer Services,Farming/Seeds/Milling,bwake2a@cnn.com,0 Orin Plaza,Kansas City,MO,64114
83,956,8/18/19,1,"$43,000.00","$21,400.00",Babbleset,Consumer Services,Farming/Seeds/Milling,bwake2a@cnn.com,0 Orin Plaza,Kansas City,MO,64114
88,374,5/1/19,1,"$32,000.00","$7,000.00",Photobug,Finance,Major Banks,mrosenwald2f@reuters.com,8 Village Place,Kansas City,MO,64187
92,760,12/28/19,1,"$31,000.00","$23,900.00",Kayveo,Health Care,Major Pharmaceuticals,htocher2j@gmpg.org,8 Debra Place,New Orleans,LA,70129
93,375,3/16/19,1,"$39,000.00","$8,000.00",Bluezoom,Public Utilities,Telecommunications Equipment,ybrickhill2k@whitehouse.gov,19 Vidon Place,Pasadena,CA,91186
95,85,8/13/19,1,"$17,000.00","$21,700.00",Fanoodle,Technology,Electrical Products,dkohen2m@a8.net,812 Northland Circle,Tulsa,OK,74156
96,257,7/2/19,1,"$96,000.00","$23,200.00",Devify,Finance,Major Banks,apittman2n@i2i.jp,0 Stoughton Street,Schenectady,NY,12325
98,776,7/12/19,1,"$86,000.00","$20,900.00",Oloo,,NaN,dhaugeh2p@census.gov,85511 Vahlen Avenue,Richmond,VA,23237
107,278,4/21/19,1,"$94,000.00","$17,400.00",Flashset,Health Care,Medical Specialities,mstummeyer2y@npr.org,236 Weeping Birch Parkway,Dallas,TX,75216
111,132,8/14/19,1,"$93,000.00","$6,000.00",Devcast,Consumer Services,Hotels/Resorts,pabelevitz32@seesaa.net,8700 Roxbury Street,Morgantown,WV,26505
121,491,11/6/19,1,"$12,000.00","$9,600.00",Zoonoodle,Health Care,Major Pharmaceuticals,vgarraway3c@sina.com.cn,1709 Waxwing Park,Los Angeles,CA,90094
128,248,3/17/19,1,"$19,000.00","$6,300.00",Zoombox,Energy,Oil Refining/Marketing,bhowlett3j@hhs.gov,43 Autumn Leaf Drive,Philadelphia,PA,19146
129,388,5/9/19,1,"$59,000.00","$8,200.00",Edgetag,,NaN,hwinship3k@rediff.com,32 Pennsylvania Point,Las Vegas,NV,89155
131,492,5/22/19,1,"$81,000.00","$13,200.00",Midel,Finance,Investment Managers,cdrennan3m@artisteer.com,0 Warner Point,Topeka,KS,66617
134,191,4/19/19,1,"$20,000.00","$8,500.00",Zava,Capital Goods,Industrial Specialties,tborges3p@mapy.cz,5 Magdeline Plaza,Wilmington,DE,19886
143,321,1/23/19,1,"$15,000.00","$5,900.00",Thoughtblab,,NaN,htonna3y@wikimedia.org,23 Algoma Road,Clearwater,FL,33758
156,616,1/31/19,1,"$16,000.00","$23,200.00",Omba,Energy,Coal Mining,mjeandin4b@nih.gov,4 Kinsman Plaza,Austin,TX,78749
163,697,9/12/19,1,"$15,000.00","$13,400.00",Feedbug,,NaN,csemeradova4i@irs.gov,3256 Bobwhite Point,Boise,ID,83732
171,814,7/6/19,1,"$49,000.00","$9,300.00",Geba,Consumer Durables,Automotive Aftermarket,cazemar4q@hhs.gov,3 Riverside Center,Tulsa,OK,74141
173,713,3/28/19,1,"$52,000.00","$18,900.00",Jabberstorm,Consumer Non-Durables,Beverages (Production/Distribution),apickthall4s@wordpress.com,454 High Crossing Court,Raleigh,NC,27626
183,944,3/20/19,1,"$39,000.00","$9,600.00",Bubblebox,Finance,Major Banks,kklageman52@about.me,6298 Maryland Center,Erie,PA,16510
187,226,10/13/19,1,"$77,000.00","$9,600.00",Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
187,768,11/2/19,1,"$94,000.00","$12,700.00",Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
193,536,3/3/19,1,"$44,000.00","$17,800.00",Mymm,,NaN,vfair5c@deviantart.com,3844 Clarendon Court,Austin,TX,78759
200,973,8/21/19,1,"$47,000.00","$12,300.00",Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055

In [5]:
list(df.loc[df['state'] == 'FL', 'company'].unique())

['Skyba',
 'Blogtags',
 'Devpoint',
 'Flipbug',
 'Jaxworks',
 'Thoughtstorm',
 'Realbuzz',
 'Dablist',
 'Fiveclub',
 'Thoughtblab',
 'Eire',
 'Mita',
 'Realmix',
 'Livefish',
 'Pixope']

In [9]:
import re
for each in ['deposit', 'monthly_amt']:
    df.loc[:, each]= pd.to_numeric([re.sub('[^0-9.]','',str(s)) for s in df[each]])

df

,contract_id,contract_start,contract_term,deposit,monthly_amt,company,sector,industry,email,address,city,state,zip
customer_id,,,,,,,,,,,,,
1,41,5/31/19,24,86000.0,11200.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,358,6/18/19,13,74000.0,19000.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,400,8/11/19,19,38000.0,8800.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,424,3/13/19,15,77000.0,14300.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
1,438,10/16/19,22,39000.0,20000.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,284,12/28/19,17,78000.0,17600.0,Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055
200,540,4/17/19,3,65000.0,9800.0,Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055
200,630,11/1/19,12,85000.0,12600.0,Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055
200,862,10/2/19,21,48000.0,6500.0,Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055
200,973,8/21/19,1,47000.0,12300.0,Kwinu,Health Care,Biotechnology: Biological Products (No Diagnos...,nrenak5j@tripadvisor.com,80 Valley Edge Park,Los Angeles,CA,90055

In [11]:
df['contract_amount'] = df['deposit'] + (df['contract_term'] * df['monthly_amt'])
df.head()

,contract_id,contract_start,contract_term,deposit,monthly_amt,company,sector,industry,email,address,city,state,zip,contract_amount
customer_id,,,,,,,,,,,,,,
1,41,5/31/19,24,86000.0,11200.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170,354800.0
1,358,6/18/19,13,74000.0,19000.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170,321000.0
1,400,8/11/19,19,38000.0,8800.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170,205200.0
1,424,3/13/19,15,77000.0,14300.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170,291500.0
1,438,10/16/19,22,39000.0,20000.0,Bubblebox,Capital Goods,Military/Government/Technical,kyerson0@bizjournals.com,76 Randy Circle,San Diego,CA,92170,479000.0

In [14]:
x = 'this is a practice test to see if this works'
print(x)

this is a practice test to see if this works